# Generated by Django 6.0.5 on 2026-05-16 19:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0003_alter_carpart_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carpart',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
        migrations.AlterField(
            model_name='carpart',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpart_set', to='parts.category'),
        ),
        migrations.AlterField(
            model_name='carpart',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='carpart',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='parts'),
        ),
    ]
