# Generated by Django 6.0.5 on 2026-05-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0005_contactmessage_coupon_order_orderitem_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpart',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='carpart',
            name='vehicle_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
